# Host with the Most: 
## Maximizing Airbnb Profits in Los Angeles with Data-Driven Insights

In [2]:
# importing libraries
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
import seaborn as sns
from matplotlib import gridspec
import plotly.figure_factory as ff
import plotly.graph_objects as go
plt.style.use('ggplot')

In [4]:
# importing dataset
calendar = pd.read_csv('data/calendar.csv.gz', encoding='utf-8-sig')
# previewing first 5 rows and last 5 rows of the dataset
calendar.head().append(calendar.tail())

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,109,2022-12-07,f,$115.00,$115.00,30.0,730.0
1,109,2022-12-08,f,$115.00,$115.00,30.0,730.0
2,109,2022-12-09,f,$115.00,$115.00,30.0,730.0
3,109,2022-12-10,f,$115.00,$115.00,30.0,730.0
4,109,2022-12-11,f,$115.00,$115.00,30.0,730.0
14758042,775316807460359720,2023-12-02,f,$500.00,$500.00,7.0,365.0
14758043,775316807460359720,2023-12-03,f,$500.00,$500.00,7.0,365.0
14758044,775316807460359720,2023-12-04,f,$500.00,$500.00,7.0,365.0
14758045,775316807460359720,2023-12-05,f,$500.00,$500.00,7.0,365.0
14758046,775316807460359720,2023-12-06,f,$500.00,$500.00,7.0,365.0

In [5]:
# saving final df as a new csv file.
calendar.to_csv('data/calendar.csv', encoding='utf-8-sig',index=False)

In [6]:
listings = pd.read_csv('data/listings.csv', encoding='utf-8-sig')

In [7]:
# saving final df as a new csv file.
listings.to_csv('data/listings.csv', encoding='utf-8-sig',index=False)